DROP TABLE IF EXISTS USER;
DROP TABLE IF EXISTS ACCOUNT;
DROP TABLE IF EXISTS CARD;

CREATE TABLE USER (
    id INT AUTO_INCREMENT PRIMARY KEY,
    username VARCHAR NOT NULL,
    password VARCHAR NOT NULL,
    enable BOOLEAN NOT NULL
);
CREATE TABLE ACCOUNT(
    id INT AUTO_INCREMENT PRIMARY KEY,
    user_id INT NOT NULL,
    balance INT NOT NULL,
    FOREIGN KEY (user_id) REFERENCES USER (id) ON DELETE CASCADE
);
CREATE TABLE CARD(
    id INT AUTO_INCREMENT PRIMARY KEY,
    account_id INT NOT NULL,
    spending_limit INT NOT NULL,
    card_number VARCHAR(16) NOT NULL,
    FOREIGN KEY (account_id) REFERENCES ACCOUNT (id) ON DELETE CASCADE
);